### ISSUE TITLE
源代码是否已经无法使用

### ISSUE THREAD

**Issue by RainySY** [feifanyl/zjyqd#4]
我在你的示列网站上无法登录。自己重新建立的网站依旧无法登录
![image](https://user-images.githubusercontent.com/58517274/111933636-d4b4ae00-8afa-11eb-901a-425a529ff758.png)

**Comment by feifanyl** [comment]
可以使用，你试一试直接将账号密码写入数据库，然后访问cs.php看看输出结果




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "feifanyl/zjyqd"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月22日(星期一) 上午10:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[feifanyl/zjyqd] 源代码是否已经无法使用 (#4)





 
我在你的示列网站上无法登录。自己重新建立的网站依旧无法登录

**Comment by chenaidairong** [comment]
好了，我直接在数据库里面添加之后可以使用了，但是这个index.php你看什么时候有空修一下，我个人认为可以把账号判断给删了

**Comment by feifanyl** [comment]
判定在check里面，如果删除的话，被人一直post乱加账号就不好了，到时候维护不方便，本人也是小白，宁愿加不进去也不让乱来



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rainy season ***@***.***&gt;; 
发送时间: 2021年3月22日(星期一) 中午11:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [feifanyl/zjyqd] 源代码是否已经无法使用 (#4)





 
好了，我直接在数据库里面添加之后可以使用了，但是这个index.php你看什么时候有空修一下，我个人认为可以把账号判断给删了
